"""update models

Revision ID: 75bb937d35ad
Revises: 18fb5b65cead
Create Date: 2026-08-16 21:53:41.118617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bb937d35ad'
down_revision: Union[str, Sequence[str], None] = '18fb5b65cead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('episode_number', sa.Integer(), nullable=False))
    op.add_column('episodes', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('episodes', sa.Column('content_group', sa.String(length=255), nullable=True))
    op.add_column('episodes', sa.Column('artwork', sa.Boolean(), nullable=True))
    op.alter_column('episodes', 'language',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_column('episodes', 'duration')
    op.add_column('shows', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'shows', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='unique')
    op.drop_column('shows', 'slug')
    op.add_column('episodes', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('episodes', 'language',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('episodes', 'artwork')
    op.drop_column('episodes', 'content_group')
    op.drop_column('episodes', 'duration_seconds')
    op.drop_column('episodes', 'episode_number')
    # ### end Alembic commands ###
